#!/bin/ksh

. ./democonfig

bin/${TEC_UNAME}/client -OpenbusHost $HostBus -OpenbusPort $PortBus -OpenbusDebug ALL -EntityName $EntityName -PrivateKeyFilename $PrivateKeyFilename -ACSCertificateFilename $ACSCertificateFilename  -FacetName $FacetName "$@"
