
module openbus {
  module legacy {
    module v1_5 {
      typedef string UUID;
      typedef UUID Identifier;
      typedef Identifier CredentialIdentifier;

      struct Credential {
        CredentialIdentifier identifier;
        string owner;
        string delegate;
      };
    };
  };
};
