#!/bin/ksh

tests="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22"

cd tests
$TECMAKE_HOME/tecmake MF=01 genstubs $@
for test in $tests ; do
  $TECMAKE_HOME/tecmake MF=$test $@
done
