
FIND_PATH(ORBIX_ROOT_DIR
  NAMES asp/6.3/bin/itconfigure
)
MARK_AS_ADVANCED(ORBIX_ROOT_DIR)

FIND_PATH(ORBIX_INCLUDE_DIR
  NAMES orbix/corba.hh
  PATHS ${ORBIX_ROOT_DIR}/asp/6.3/include
)

FIND_PROGRAM(ORBIX_COMPILER_IDL idl
  PATHS ${ORBIX_ROOT_DIR}/asp/6.3/bin
)

INCLUDE(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Orbix DEFAULT_MSG
  ORBIX_LIBRARIES 
  ORBIX_INCLUDE_DIR
  ORBIX_COMPILER_IDL
)

FUNCTION (orbix_idl idlfile)
  GET_FILENAME_COMPONENT(ORBIX_SOURCE_FILENAME ${idlfile} NAME)
  GET_FILENAME_COMPONENT(ORBIX_SOURCE_FILENAME_WE ${idlfile} NAME_WE)
  SET(ORBIX_IDL_PARAMS)
  MATH(EXPR CURRENT_ARG 1)
  # ARGS
  IF(${ARGC} GREATER "${CURRENT_ARG}" AND "${ARGV${CURRENT_ARG}}" STREQUAL "ARGS")
    MATH(EXPR CURRENT_ARG ${CURRENT_ARG}+1)
    WHILE((NOT "${CURRENT_ARG}" EQUAL "{ARGC}") AND (NOT ${ARGV${CURRENT_ARG}} STREQUAL "DEPENDS"))
      SET(ORBIX_IDL_ARGS ${ORBIX_IDL_ARGS} ${ARGV${CURRENT_ARG}})
      MATH(EXPR CURRENT_ARG ${CURRENT_ARG}+1)
    ENDWHILE((NOT "${CURRENT_ARG}" EQUAL "{ARGC}") AND (NOT ${ARGV${CURRENT_ARG}} STREQUAL "DEPENDS"))
  ENDIF(${ARGC} GREATER "${CURRENT_ARG}" AND "${ARGV${CURRENT_ARG}}" STREQUAL "ARGS")
  # DEPENDS
  IF("${ARGC}" GREATER "${CURRENT_ARG}" AND "${ARGV${CURRENT_ARG}}" STREQUAL "DEPENDS")
    MATH(EXPR CURRENT_ARG ${CURRENT_ARG}+1)
    WHILE(NOT ("${CURRENT_ARG}" STREQUAL "${ARGC}"))
      SET(ORBIX_IDL_DEPENDS ${ORBIX_IDL_DEPENDS} ${ARGV${CURRENT_ARG}})
      MATH(EXPR CURRENT_ARG ${CURRENT_ARG}+1)
    ENDWHILE(NOT ("${CURRENT_ARG}" STREQUAL "${ARGC}"))
  ENDIF("${ARGC}" GREATER "${CURRENT_ARG}" AND "${ARGV${CURRENT_ARG}}" STREQUAL "DEPENDS")

  ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME}
    COMMAND cp ${idlfile} ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    DEPENDS ${idlfile}
  )
  ADD_CUSTOM_COMMAND(
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME_WE}S.hh
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME_WE}S.cxx
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME_WE}.hh
    OUTPUT ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME_WE}C.cxx
    COMMAND ${ORBIX_COMPILER_IDL} ${ORBIX_IDL_ARGS} ${ORBIX_SOURCE_FILENAME}
    WORKING_DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}
    MAIN_DEPENDENCY ${CMAKE_CURRENT_BINARY_DIR}/${ORBIX_SOURCE_FILENAME}
    DEPENDS ${ORBIX_IDL_DEPENDS}
  )
ENDFUNCTION (orbix_idl)

mark_as_advanced(ORBIX_LIBRARIES ORBIX_INCLUDE_DIR ORBIX_COMPILER_IDL)
