#!/bin/ksh

. ./democonfig

bin/hello_server-mico-mt-s -OpenbusHost $HostBus -OpenbusPort $PortBus -OpenbusDebug ALL -EntityName $EntityName -PrivateKeyFilename $PrivateKeyFilename -ACSCertificateFilename $ACSCertificateFilename  -FacetName $FacetName "$@"
