#!/bin/ksh

. ./democonfig

bin/server -OpenbusHost $HostBus -OpenbusPort $PortBus -OpenbusDebug ALL -EntityName $EntityName -PrivateKeyFilename $PrivateKeyFilename -ACSCertificateFilename $ACSCertificateFilename  -FacetName $FacetName "$@"
